### ISSUE TITLE
Ansible Play book is not run on Node ,how can i fix issue?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#762]
![Ansible issue](https://user-images.githubusercontent.com/55782151/76427401-3f081e00-63d2-11ea-88b7-60f98d0b6b93.PNG)

Ansible play book

---
- hosts: all
  become: yes
  tasks:
    - name: install java and update packages
      apt:
        name: openjdk-8-jdk
        update: yes
        state: present
    - name: download spring pet clinic
      get_url:
        url: https://get.spc.com/jar
        dest: /home/devops/spc.jar
        state: present
    - name: execute java jar
      command: java -jar /home/devops/spc.jar

**Comment by dhana9000** [comment]
Hi prasadsai,
Update parameter is not present in apt module.
To update packages we have to use "update_cache: yes"

**Comment by srmanikanta** [comment]
### hi, prasad please follow this playbook reference
```
---
- hosts: all
  become: yes
  tasks:
  - name: install java and update packages
     apt:
       name: openjdk-8-jdk
       update_cache: yes
       state: present
  - name: download spring pet clinic
     get_url:
       url: https://get.spc.com/jar
       dest: /home/devops/spc.jar
  - name: execute java jar
    shell: nohup java -jar /home/devops/spc.jar & 
```
In your playbook you did the some mistakes but i corrected please follow the ansible official document before you write any playbook.
