### ISSUE TITLE
executing the command in ansible

### ISSUE THREAD

**Issue by Rajulolabhattu** [QT-DevOps/DevOpsIssues#811]
Want to execute the highlighted command once while running the playbook at once if the playbook run more than twice i junt want to skip the highlighted part can anyone help to solve the problem
![Screenshot (80)](https://user-images.githubusercontent.com/62057171/79549439-9aee5280-80b4-11ea-9d66-2710d33692f3.png)

**Comment by NareshAbbanapuri** [comment]
hi
that task write in handlers use where you want
Or
by using when condition we can make as idempotent

**Comment by Rajulolabhattu** [comment]
yes naresh i am also want to use when condition but im unable to write when condition could u help me for that

**Comment by srmanikanta** [comment]
hi raju 
if you make non-idempotent module idempotent you actually two possible solution are there
1. environment variables
2. create a file
In the below I gave the file creation example
  ```
 - name: check if the file exists
    stat:
      path: /home/devops/commad.txt
    register: stat_op
 - name: execute command
    command: echo "hello" > /home/devops/commad.txt
    when: stat_op.stat.exists == False
   ```
use this process in your task when the task get execute it will check the file is exist or not if exist skip this process otherwise it create a file and execute the remaining commands.
