### ISSUE TITLE
SSH session could not be established

### ISSUE THREAD

**Issue by allagaddaraviteja** [QT-DevOps/DevOpsIssues#835]
Im trying to launch two instances in aws both instances are getting created but second instance throwing ssh error while creating vm
<img width="640" alt="error1" src="https://user-images.githubusercontent.com/47173658/80085655-29137e80-8576-11ea-8c3f-8765b0f74e33.PNG">
<img width="907" alt="error2" src="https://user-images.githubusercontent.com/47173658/80085664-2b75d880-8576-11ea-8375-f4c96ea7b2ca.PNG">
<img width="504" alt="vm" src="https://user-images.githubusercontent.com/47173658/80085665-2c0e6f00-8576-11ea-8318-e13665a0dccb.PNG">
<img width="600" alt="yml" src="https://user-images.githubusercontent.com/47173658/80085669-2ca70580-8576-11ea-9129-3913d4604092.PNG">
<img width="616" alt="yml1" src="https://user-images.githubusercontent.com/47173658/80085672-2d3f9c00-8576-11ea-968d-17fde0d900fa.PNG">

**Comment by srmanikanta** [comment]
you have to specify the sunbnet, keypair,security group..etc. for second instance in driver section.
how you are specify the first instance then you have to mention those all are related to your second instance too like
from driver to provisionar whats specification are mentioned in instance one those all specification are mention  in second instance too (but suites is configure once for both at the end) 
try like this and update the issue accordingly

**Comment by allagaddaraviteja** [comment]
Even after updating all the details getting same error.
<img width="596" alt="error3" src="https://user-images.githubusercontent.com/47173658/80105277-f8dbd800-8595-11ea-83a1-4e9c293f717b.PNG">

<img width="896" alt="error5" src="https://user-images.githubusercontent.com/47173658/80105307-0b561180-8596-11ea-822a-06d989894e04.PNG">

<img width="944" alt="error4" src="https://user-images.githubusercontent.com/47173658/80105328-1741d380-8596-11ea-978e-044bc0fae2c5.PNG">

<img width="504" alt="vm" src="https://user-images.githubusercontent.com/47173658/80105375-27f24980-8596-11ea-9146-b7d4b988944b.PNG">


<img width="604" alt="yml2" src="https://user-images.githubusercontent.com/47173658/80105415-33457500-8596-11ea-8191-4f4577cb7ff2.PNG">

<img width="561" alt="yml3" src="https://user-images.githubusercontent.com/47173658/80105463-448e8180-8596-11ea-89fd-f8760de4068d.PNG">

<img width="308" alt="yml4" src="https://user-images.githubusercontent.com/47173658/80105469-45bfae80-8596-11ea-94a6-a0a6496ad8e4.PNG">

but in class sir did this changes only

<img width="300" alt="class" src="https://user-images.githubusercontent.com/47173658/80105675-861f2c80-8596-11ea-9618-1a6b380af921.PNG">

**Comment by rpkoya** [comment]
HI Raviteja,

Its alignment issue in your kitchen file, you are placing driver and transport inside platforms,
Please align those two statements as per below screenshot and check
![80085672-2d3f9c00-8576-11ea-968d-17fde0d900fa](https://user-images.githubusercontent.com/63572053/80166137-d4661700-85fa-11ea-9c8e-ef5452c78a9d.png)

**Comment by srmanikanta** [comment]
follow this approach and do not copy paste the below configuration, please change according to your aws region and default vpc and one more thing is please check the ami is working manually or not (especially centos).
This the kitchen.yml file for both ubuntu and centos 
```
---
driver:
  name: ec2
  aws_ssh_key_id: elasticsearch
  region: us-east-2
  availability_zone: us-east-2a
  subnet_id: subnet-6602050e
  instance_type: t2.micro
  image_id: ami-0d5d9d301c853a04a
  security_group_ids: ["sg-0eeb8a9322eb69c42"]

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

transport: 
  ssh_key: ./elasticsearch.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu 

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: centos-7
    driver:
      name: ec2
      aws_ssh_key_id: elasticsearch
      region: us-east-2
      availability_zone: us-east-2a
      subnet_id: subnet-6602050e
      instance_type: t2.micro
      image_id: ami-0f2b4fc905b0bd1f1
      security_group_ids: ["sg-0eeb8a9322eb69c42"]
    transport:
      username: centos
      ssh_key: ./elasticsearch.pem
      connection_timeout: 10
      connection_retries: 5
    provisioner:
      name: chef_zero
    verifier:
      name: inspec
    
    
suites:
  - name: default
    run_list:
      - recipe[apachewithphp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

```
this configuration working and please change the values related to you aws.
